name: Trigger auto deployment for fiap-tech-challange-admin-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fiap-tech-challange-admin-app-AutoDeployTrigger-d068a0a7-2868-4b4f-be37-b1a3ec2c60e9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FIAPTECHCHALLANGEADMINAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FIAPTECHCHALLANGEADMINAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FIAPTECHCHALLANGEADMINAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FIAPTECHCHALLANGEADMINAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIAPTECHCHALLANGEADMINAPP_REGISTRY_PASSWORD }}
          containerAppName: fiap-tech-challange-admin-app
          resourceGroup: fiap-tech-challenge-admin-group
          imageToBuild: cangelosilima/fiap-tech-challange-admin-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


